"""esquema inicial

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('criticalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('observed', sa.Integer(), nullable=False),
    sa.Column('n1_codes', sa.Integer(), nullable=False),
    sa.Column('n2_codes', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services_l1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('code_original', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('source_range', sa.String(length=200), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_area_company_code')
    )
    op.create_index(op.f('ix_areas_company_id'), 'areas', ['company_id'], unique=False)
    op.create_table('import_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('sheet', sa.String(length=100), nullable=True),
    sa.Column('row_ref', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_observations_run_id'), 'import_observations', ['run_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'code', name='uq_department_area_code')
    )
    op.create_index(op.f('ix_departments_area_id'), 'departments', ['area_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_section_department_code')
    )
    op.create_index(op.f('ix_sections_department_id'), 'sections', ['department_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'code', name='uq_position_section_code')
    )
    op.create_index(op.f('ix_positions_section_id'), 'positions', ['section_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','consulta')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_position_id'), 'users', ['position_id'], unique=False)
    op.create_table('services_l2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('code_original', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('level1_id', sa.Integer(), nullable=False),
    sa.Column('activo_excel', sa.String(length=1), nullable=True),
    sa.Column('activo_raw', sa.String(length=100), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('criticality_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric', sa.String(length=300), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=10), nullable=False),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('source_range', sa.String(length=200), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("activo_excel IS NULL OR activo_excel IN ('S','N')", name='ck_l2_activo'),
    sa.CheckConstraint("review_status IN ('ok','revisar')", name='ck_l2_review'),
    sa.CheckConstraint('min_value IS NULL OR max_value IS NULL OR min_value <= max_value', name='ck_l2_min_max'),
    sa.ForeignKeyConstraint(['class_id'], ['service_classes.id'], ),
    sa.ForeignKeyConstraint(['criticality_id'], ['criticalities.id'], ),
    sa.ForeignKeyConstraint(['level1_id'], ['services_l1.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_services_l2_level1_id'), 'services_l2', ['level1_id'], unique=False)
    op.create_index(op.f('ix_services_l2_responsible_user_id'), 'services_l2', ['responsible_user_id'], unique=False)
    op.create_index(op.f('ix_services_l2_section_id'), 'services_l2', ['section_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_services_l2_section_id'), table_name='services_l2')
    op.drop_index(op.f('ix_services_l2_responsible_user_id'), table_name='services_l2')
    op.drop_index(op.f('ix_services_l2_level1_id'), table_name='services_l2')
    op.drop_table('services_l2')
    op.drop_index(op.f('ix_users_position_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_positions_section_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_sections_department_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_departments_area_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_import_observations_run_id'), table_name='import_observations')
    op.drop_table('import_observations')
    op.drop_index(op.f('ix_areas_company_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_table('services_l1')
    op.drop_table('service_types')
    op.drop_table('service_classes')
    op.drop_table('import_runs')
    op.drop_table('criticalities')
    op.drop_table('companies')
    # ### end Alembic commands ###
